In [210]:
s='datA sCience'
s = s.lower()
words = s.split(' ')
final_list = [word.title() for word in words]
final_string = '_'.join(final_list)
final_string

'Data_Science'

In [91]:
output_dict= {val : val**3 for val in input_list if val % 3 == 0}
print(output_dict)

{3: 27, 6: 216, 9: 729, 12: 1728, 15: 3375, 18: 5832, 21: 9261, 24: 13824, 27: 19683, 30: 27000, 33: 35937, 36: 46656, 39: 59319, 42: 74088, 45: 91125, 48: 110592, 51: 132651, 54: 157464, 57: 185193, 60: 216000, 63: 250047, 66: 287496, 69: 328509, 72: 373248, 75: 421875, 78: 474552, 81: 531441, 84: 592704, 87: 658503, 90: 729000, 93: 804357, 96: 884736, 99: 970299}


In [213]:
s = 'programming'

vowel = "aeiouAEIOU"

v = ""
c = ""

for i in s:
    if i in vowel:
        v = v+i
    else:
        c = c+i

final = v+c
print(final)

oaiprgrmmng


In [225]:
s1 = "upgrad"
s2 = "upgradScience"

s1 = s1.lower()
s2 = s2.lower()
min_len = min(len(s1),len(s2))

for i in range(min_len):
    if s1[i] != s2[i]:
        break
if i == 0:
    print(-1)
elif i == min_len-1:
    print(s1[:i+1])
else:
    print(s1[:i])
print(i, min_len)
    
        

upgrad
5 6


In [230]:
s1 = "night"
s2 = "thing"

s1 = s1.lower()
s2 = s2.lower()

for i in range(len(s1)):
    if s1[i] not in s2:
        print("Not anagrams")
        break
if i == len(s1)-1:
    print('Anagrams')

Anagrams


In [253]:
dict_1 = {"Python":40, "R":45}
del dict_1['R']
dict_1

{'Python': 40}

In [ ]:
import ast

mylist=ast.literal_eval(input())

In [258]:
inp = "){[[]]}())()"

stack = []

for i in inp:
    if len(stack)==0:
        stack.append(i)
    else:
        if i == ')'and stack[-1]=='(':
            stack.pop()
        if i == '}'and stack[-1]=='{':
            stack.pop()
        if i == ']'and stack[-1]=='[':
            stack.pop()
        else:
            stack.append(i)

if stack:
    print("No")
else:
    print("Yes")

No


In [262]:
1**3

1

In [269]:
s = "I love Python"
s[3:7]

'ove '

In [273]:
3*3**3

81

In [274]:
T = (3,5,7,11)
T.append(9)

AttributeError: 'tuple' object has no attribute 'append'

In [275]:
L1 = ['Vikas', 'Akshay', 'Sanskar', 'Mahima']
print(L1[1][-1])

y


In [277]:
l = [32, 34, 12, 27, 33]
l.append([14, 19])
print(l)

[32, 34, 12, 27, 33, [14, 19]]


In [278]:
D = {1:['Raj', 22], 2:['Simran', 21], 3:['Rahul', 40]}
for val in D:
     print(val)

1
2
3


In [279]:
print(list(range(10, 1, -1)))

[10, 9, 8, 7, 6, 5, 4, 3, 2]


In [285]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[2:-3])
print(array_1[ : : -2])
array_1[1: : 2]

[3, 5, 4, 6, 7, 8]
[2, 5, 7, 4, 3, 1]


[2, 5, 6, 8, 3]

In [296]:
import numpy as np
n=2
ones = np.ones((n,n), dtype=int)

if n >2:
    for i in range(1,n-1):
        for j in range(1,n-1):
            ones[i][j]=0
print(ones)



[[1 1]
 [1 1]]


In [389]:
import numpy as np

a=np.arange(64).reshape(8,8)

a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [391]:
a[:3,-5:]

array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23]])

In [392]:
np.arange(1,16,2).reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [298]:
p = [[1, 5],
 [3, 7],
 [4, 9]]

np.reshape(p,-1)

array([1, 5, 3, 7, 4, 9])

In [304]:
array = [[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]]

array_1 = np.array(array)


print(array_1[array_1%2 != 0].reshape(5, 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [305]:
p = [[1, 5],
 [3, 7],
 [4, 9]]

np.reshape(p,(1,-1))

array([[1, 5, 3, 7, 4, 9]])

In [345]:
list_1 = [[7, 13, 14], [18, 10, 17], [11, 12, 19]]
list_2 = [16, 6, 1]
list_3 = [[5, 8, 4, 3]]

list_1.append(list_2)


for i in range(len(list_1)):
    list_1[i].append(list_3[0][i])

final_array = np.array(list_1)
print(final_array)


[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [323]:
c[0]

array([5, 8, 4, 3])

In [354]:
import pandas as pd

df = {'S.No.':[1,2,3,4,5],"Name": ["Akshay",'Mahima','Vikas', 'Abhinav', 'Mahima'],"Subject":['Maths','English','Maths','English','Science'],'Maximum Marks':[50, 40,50,40,50],'Marks Obtained':[40,33,42,31,40], 'Percentage':[80,83,84,78,80] }

df = pd.DataFrame(df)

df.index = df['S.No.']

df = df[['Name','Subject','Maximum Marks','Marks Obtained','Percentage']]

df

Name  Subject  Maximum Marks  Marks Obtained  Percentage
S.No.                                                             
1       Akshay    Maths             50              40          80
2       Mahima  English             40              33          83
3        Vikas    Maths             50              42          84
4      Abhinav  English             40              31          78
5       Mahima  Science             50              40          80

In [358]:
df.loc[[2], [0, 1, 4]]

KeyError: "None of [Int64Index([0, 1, 4], dtype='int64')] are in the [columns]"

In [363]:
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv')

df['Training'] = df['Rating'].apply(lambda x: "Yes" if x<=3.5 else "No")

for i in set(df['Department']):
              total_emps  = len(df[(df['Department']==i)])
              trainees = len(df[(df['Department']==i) & (df['Training']=='Yes')])
              perc = trainees *100/total_emps
              print(i, total_emps, trainees, perc)


HR 131 56 42.74809160305343
Finance 134 67 50.0
Marketing 138 74 53.6231884057971
Sales 130 66 50.76923076923077


In [364]:
df.groupby()

TypeError: You have to supply one of 'by' and 'level'

In [368]:
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
#Type your groupby command here
print(df)
df_1 = df[['month','day','rain','wind']].groupby(['month','day']).mean()
df_1

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]


rain      wind
month day                
apr   fri   0.0  3.100000
      mon   0.0  3.100000
      sat   0.0  4.500000
      sun   0.0  5.666667
      thu   0.0  5.800000
...         ...       ...
sep   sat   0.0  3.460000
      sun   0.0  3.955556
      thu   0.0  3.357143
      tue   0.0  3.431579
      wed   0.0  3.378571

[64 rows x 2 columns]

In [370]:
import pandas as pd
df_1 = pd.read_csv('https://cdn.upgrad.com/uploads/production/1ed2840b-f083-44fe-9eb4-acda009ac620/restaurant-1.csv')
df_2 = pd.read_csv('https://cdn.upgrad.com/uploads/production/c87b99b4-467c-4128-8729-85bff0b0acbe/restaurant-2.csv')
print(df_1.head())
#df_3 = #Type your code here.
print(df_3.head(20))

                        name                     address             city  \
0  arnie morton's of chicago   "435 s. la cienega blvd."    "los angeles"   
1                 art's deli       "12224 ventura blvd."    "studio city"   
2              bel-air hotel      "701 stone canyon rd."        "bel air"   
3                 cafe bizou       "14016 ventura blvd."   "sherman oaks"   
4                  campanile       "624 s. la brea ave."    "los angeles"   

            cuisine unique_id  
0     "steakhouses"       '0'  
1           "delis"       '1'  
2     "californian"       '2'  
3   "french bistro"       '3'  
4     "californian"       '4'  


NameError: name 'df_3' is not defined

In [377]:
import numpy as np 
import pandas as pd

# Defining the three dataframes indicating the gold, silver, and bronze medal counts
# of different countries
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

medals = gold.append(silver.append(bronze))

print(medals.groupby('Country').sum().sort_values('Medals',ascending=False))

         Medals
Country        
USA          72
France       53
UK           27
Russia       25
Germany      20


In [386]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://cdn.upgrad.com/uploads/production/b3467ba4-4e13-44e9-8087-4d7e94cc7586/forestfires.csv')
print(df.head())
df_1 = df.pivot_table(index=['month','day'], values = ['rain','wind'],aggfunc = "mean") #Type your code here. 
print(df_1.head(20))

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0
               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
    

In [400]:
n = int(input())

zmat = np.zeros((n,n), dtype=int)

for i in range(n):
    for j in range(n):
        if i == n//2:
            zmat[i][j]=1
        if j == n//2:
            zmat[i][j]=1
    
zmat

5


array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [410]:
import matplotlib.pyplot as plt
import numpy as np

list_1 = [48.49, 67.54, 57.47, 68.17, 51.18, 68.31, 50.33, 66.7, 45.62, 43.59, 53.64, 70.08, 47.69, 61.27, 44.14, 51.62, 48.72, 65.11]

# plt.boxplot(list_1)

print(np.percentile(list_1, [0, 25, 50, 75, 100]))

[43.59   48.5475 52.63   66.3025 70.08  ]
